[package]
name = "server-pong"
version = "0.1.0"
edition = "2024"

[profile.release]
codegen-units = 1
opt-level = "z"
strip = true
panic = "abort"
lto = true

[dependencies]
axum = "0.8.1"
tokio = { version = "1.44.0", features = ["full"] }
tower = "0.5.2"
