grafana.ini:
  auth:
    disable_login_form: true
    disable_signout_menu: true

  auth.anonymous:
    enabled: true
    org_name: Main Org.
    org_role: Admin

extraConfigMaps:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.default.svc.cluster.local
        access: proxy
        isDefault: true
